Update provision_ec2.yml

diff --git a/.github/workflows/provision_ec2.yml b/.github/workflows/provision_ec2.yml
--- a/.github/workflows/provision_ec2.yml
+++ b/.github/workflows/provision_ec2.yml
@@ -41,10 +41,10 @@ jobs:
         # terraform fmt -check
         terraform plan
 
-    # # Abort if the plan failed
-    # - name: Abort on Terrafor failures
-    #   if: steps.plan.outcome == 'failure'
-    #   run: exit 1
+    # Abort if the plan failed
+    - name: Abort on Terrafor failures
+      if: steps.plan.outcome == 'failure'
+      run: exit 1
       
     # Apply the plan to the environment
     - name: Apply Terraform plan
@@ -66,17 +66,16 @@ jobs:
         name: terraform-output
         path: ${{ github.workspace }}/tf_output.sh
 
-  # verify_environment:
-  #   name: 'Verify EC2 instance'
-  #   runs-on: ubuntu-latest
-  #   needs: provision_environment
+  verify_environment:
+    name: 'Verify EC2 instance'
+    runs-on: ubuntu-latest
+    needs: provision_environment
     
-  #   steps:
+    steps:
     - name: Restore Terraform output
       uses: actions/download-artifact@v2
       with:
         name: terraform-output
-
     
     - name: Verify endpoint
       run: |
@@ -86,23 +85,23 @@ jobs:
         echo 'Pinging endpoint... '
         curl ${url}
 
-  # destroy_environment:
-  #   name: 'Destrory EC2 instance'
-  #   runs-on: ubuntu-latest
-  #   needs: verify_environment
+  destroy_environment:
+    name: 'Destrory EC2 instance'
+    runs-on: ubuntu-latest
+    needs: verify_environment
     
   #   steps:
     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
-    # - name: Setup Terraform
-    #   uses: hashicorp/setup-terraform@v1
-    #   with:
-    #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v1
+      with:
+        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
     # Initialize a new Terraform and destroy the environment
     - name: Destroy environment
       run: |
         # terraform init
-        terraform destroy
+        terraform destroy -auto-approve
 
 
 
